# Generated by Django 3.2.5 on 2021-11-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='assignments'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='icons'),
        ),
        migrations.AlterField(
            model_name='illustration',
            name='image',
            field=models.ImageField(blank=True, upload_to='diagrams'),
        ),
        migrations.AlterField(
            model_name='response',
            name='file1',
            field=models.FileField(null=True, upload_to='assignmets'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='icons'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='syllabus_file',
            field=models.FileField(blank=True, null=True, upload_to='syllabuses'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='material'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='icons'),
        ),
    ]
