# Generated by Django 3.2.5 on 2021-11-13 18:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elearning', '0002_auto_20211112_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='files/assignments'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='files/icons'),
        ),
        migrations.AlterField(
            model_name='illustration',
            name='image',
            field=models.ImageField(blank=True, upload_to='files/diagrams'),
        ),
        migrations.AlterField(
            model_name='response',
            name='file1',
            field=models.FileField(null=True, upload_to='files/assignments'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='files/icons'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='files/syllabuses'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='syllabus_file',
            field=models.FileField(blank=True, null=True, upload_to='files/syllabuses'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='files/material'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='files/icons'),
        ),
        migrations.CreateModel(
            name='Enrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('in_progress', models.BooleanField(default=True)),
                ('complete', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.course')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
