# Generated by Django 4.0.1 on 2022-01-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_auto_20211113_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='code',
            field=models.CharField(default='ABCD', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
