# Generated by Django 4.0.1 on 2022-01-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_alter_level_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='code',
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
