# Generated by Django 4.0.1 on 2022-01-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_remove_level_code_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(default=1234, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
