# Generated by Django 4.0.1 on 2022-02-23 11:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0008_alter_level_options_enrol_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseKeyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('covered', models.BooleanField(default=False)),
                ('average_key_point_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.course')),
            ],
        ),
    ]
