# Generated by Django 3.2.5 on 2021-08-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='topicinstance',
            name='diagram',
        ),
    ]
