# Generated by Django 3.2.5 on 2021-08-24 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210819_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='inbound_assgns')),
                ('submission', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('assessed_doc', models.FileField(upload_to='assessed_docs')),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.answer')),
            ],
        ),
        migrations.RemoveField(
            model_name='topicinstance',
            name='topic',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assign_out',
            field=models.FileField(default=1, upload_to='assign_out'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='TopicInstance',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.assignment'),
        ),
        migrations.AddField(
            model_name='answer',
            name='assign_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.profile'),
        ),
    ]
