# Generated by Django 3.2.5 on 2021-08-24 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210824_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='topic',
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.subject'),
            preserve_default=False,
        ),
    ]
