# Generated by Django 3.2.5 on 2021-08-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_coursestarted'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestarted',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
